### ISSUE TITLE
DORN gen_interpolation.py issue!!

### ISSUE THREAD

**Issue by stanny880913** [lochenchou/RCDPT#2]
May i ask how many image do i need to put in RCDPT nuscenes/samples? i know i need to create 2 folder to put LiDAR gt,but when i put 5 images in it! its still show no such file error! How can i fix it?

**Comment by lochenchou** [comment]
Actually you could use the following function to load ground truth sparse depth online during training/validation phase. And there will be no need to generate.
I don't know if this answers to your issue. 


def loadSparseDepth(nusc, sample):
    cam_token = sample['camera_token']
    lidar_token = sample['lidar_token']
    points, coloring, im = nusc.explorer.map_pointcloud_to_image(pointsensor_token=lidar_token,camera_token=cam_token)
    sparse_depth = np.zeros((450,800))
    sparse_depth[(points[1][:]/2).astype(np.int), (points[0][:]/2).astype(np.int)] = coloring
    return sparse_depth

**Comment by stanny880913** [comment]
> Actually you could use the following function to load ground truth sparse depth online during training/validation phase. And there will be no need to generate. I don't know if this answers to your issue.
> 
> def loadSparseDepth(nusc, sample): cam_token = sample['camera_token'] lidar_token = sample['lidar_token'] points, coloring, im = nusc.explorer.map_pointcloud_to_image(pointsensor_token=lidar_token,camera_token=cam_token) sparse_depth = np.zeros((450,800)) sparse_depth[(points[1][:]/2).astype(np.int), (points[0][:]/2).astype(np.int)] = coloring return sparse_depth


where can put this function?
And where to call it?
Thx!

**Comment by stanny880913** [comment]
> Actually you could use the following function to load ground truth sparse depth online during training/validation phase. And there will be no need to generate. I don't know if this answers to your issue.
> 
> def loadSparseDepth(nusc, sample): cam_token = sample['camera_token'] lidar_token = sample['lidar_token'] points, coloring, im = nusc.explorer.map_pointcloud_to_image(pointsensor_token=lidar_token,camera_token=cam_token) sparse_depth = np.zeros((450,800)) sparse_depth[(points[1][:]/2).astype(np.int), (points[0][:]/2).astype(np.int)] = coloring return sparse_depth

Sorry，maybe really need your help，i don't know where to put it and call it，i tried many times but still error : (

**Comment by lochenchou** [comment]
If you still have the same issue, you could let me know it.
Otherwise, I would recommend you to go through again the official tutorial jupyter notebook file.
